# **PyTorch Basics: Tensors & Gradients:**

PyTorch supports automatic differentiation, which enables efficient computation of gradients for training neural networks using backpropagation. It provides a rich set of tools and libraries for tasks such as data loading, model building, optimization, and evaluation.
<br>
<br>

One of the key advantages of PyTorch is its support for GPU acceleration, allowing to train models on GPUs to significantly speed up computations.
<br>
<br>

While TensorFlow focuses more on static computation graphs, PyTorch emphasizes dynamic computation graphs. This fundamental difference in design philosophy gives PyTorch an edge when it comes to flexibility and ease of use.
<br>
<br>

Overall, PyTorch is widely used in the research community.


##**Main Advantage of PyTorch is:**
It can automatically calculate derivatives. Just need to flag it true and the other one is GPU support.

In [ ]:
 import torch

#**Tensors:**

###**Number/Scaler:**

In [ ]:
t1 = torch.tensor(4.)  # 4. is a shorthand notation for 4.0
t1

tensor(4.)

In [ ]:
t1.dtype

torch.float32

#**Vector**:

In [ ]:
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

#**Matrix:**

In [ ]:
t3 = torch.tensor([
    [5., 6],
    [7,8],
    [9,10]
])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

#**Dimnesional Array:**

In [ ]:
t4 = torch.tensor([
    [
        [11, 12, 13],
        [14, 15, 16]
    ],
    [
        [17,18,19],
        [20,21,22]
    ]
])

t4

tensor([[[11, 12, 13],
         [14, 15, 16]],

        [[17, 18, 19],
         [20, 21, 22]]])

In [ ]:
t4.shape # [2,2,3] - 2 matrices 2X3

torch.Size([2, 2, 3])

In [ ]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [ ]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [ ]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [ ]:
print(t4)
t4.shape

tensor([[[11, 12, 13],
         [14, 15, 16]],

        [[17, 18, 19],
         [20, 21, 22]]])


torch.Size([2, 2, 3])

#**Tensor Operation and Gradients:**

In [ ]:
x = torch.tensor(3.) # Input
w = torch.tensor(4. , requires_grad = True) # Weight
b = torch.tensor(5., requires_grad = True) # Bias

x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

#**Arithmatic Operation:**

In [ ]:
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

#**Compute Derivates:**

In [ ]:
y.backward()

#**Displaying Gradients:**

In [ ]:
print("dy/dx: ",x.grad)
print("dy/dw: ",w.grad)
print("dy/db: ",b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


#**Tensor Functions:**

In [ ]:
t6 = torch.full((3,2),42) # Creates a tensor of shape (3 rows, 2 columns) where every value is 42.
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

#**Concatinate two tensors with compatible shapes:**

In [ ]:
t7 = torch.cat((t3, t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [ ]:
t3.shape , t6.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

#**Sin of each Element:**

In [ ]:
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

# **Changing the shape of a tensor:**

In [ ]:
t9 = t8.reshape(3,2,2) # 3 blocks (or layers) , Each block has 2 rows ,Each row has 2 columns
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

# **Interoperability with Numpy:**

In [ ]:
import numpy as np

x = np.array([[1,2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

### **Numpy array into a PyTorch Tensor**:

In [ ]:
y = torch.from_numpy(x) # converts a NumPy array into a PyTorch tensor.
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [ ]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

###**PyTorch to Numpy:**

In [ ]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])